---

- hosts: webservers
  gather_facts: no
  become: yes
  become_user: root

  vars_prompt:
    - name: lastName
      prompt: What is your last name?
      private: no


  vars:
    firstName: John

  tasks:
    - name: Do print
      debug:
        msg: "{{ firstName }}"